name: js

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install latest npm
      run: |
        npm install -g npm &&
        npm --version &&
        npm list -g --depth 0
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ncmb_min_js
        path: ncmb.min.js
