name: Generate Reference 

on: [push]

jobs:
  generate_reference-and-push_ncmb_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list

    - name: Install dependencies
      run: npm install

    - name: generate reference
      run: npm run document:generate

    - name: Setup git
      env:
          EMAIL: ${{ secrets.EMAIL }}
      run: |
        git config --global user.email "$EMAIL"
        git config --global user.name "tanaka-kokoro"

    - name: Commit docs
      run: |
        git add -N ./docs/
        if ! git diff --exit-code --quiet
        then
          git commit -m "Replace docs"
          git pull
          git push origin master
        fi

    - name: zip docs
      run: zip -r docs.zip docs/

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs.zip